### ISSUE TITLE
Please fix dependency on libxcb. It is very loose and it hurts!

### ISSUE THREAD

**Issue by nehaljwani** [conda-forge/xorg-libx11-feedstock#24] opened 2021-02-26 00:52 UTC
```
root@0c38ad9ac566:/# /base_home/conda-latest-linux-64.exe search --info -c conda-forge xorg-libx11 | grep ' libxcb'
  - libxcb 1.*
  - libxcb 1.*
  - libxcb 1.*
  - libxcb 1.*
  - libxcb 1.*
  - libxcb 1.*
  - libxcb 1.*
  - libxcb 1.*
  - libxcb 1.*
  - libxcb 1.*
  - libxcb 1.*
  - libxcb 1.*
  - libxcb 1.*
  - libxcb 1.*
```

It should ideally be a range of the sort: `libxcb >=<version-used-at-build-time>,<2.0a0`

:cry: :crying_cat_face: :sob:

**Comment by pkgw** [comment] 2021-02-26 02:14
Hi —

The `xorg-libx11` packages are compatible with this wide version range of `libxcb` packages, which maintains ABI backwards compatibility pretty rigorously ([see ABI Laboratory](https://abi-laboratory.pro/index.php?view=timeline&l=libxcb)), so I would say that the loose version constraint is correct here. I'll follow up more in conda-forge/graphviz-feedstock#35 but I don't feel that the proper solution to that issue calls for any modifications to `libxcb` version constraints.

**Comment by nehaljwani** [comment] 2021-02-26 02:20
Why don't we handle this pinning at conda-forge-pinning?

I understand the loose dep, but why not keep a minimum pin, like we do for all other packages? For example, if `xorg-libx11` uses one of the new symbols brought in by `libxcb 1.13`, you would still let end users install `libxcb 1.12`. Won't that cause a problem?

cc @conda-forge/core

**Comment by pkgw** [comment] 2021-02-26 02:39
Yes, that would cause a problem, and if that were to happen it would be appropriate to bump the minimum version requirement in this package. But that isn't the case right now, to the best of my knowledge. As I commented on conda-forge/graphviz-feedstock#35, I don't think that the underlying issue there is really related to version requirements / pinning.

**Comment by pkgw** [comment] 2021-03-22 14:53
I'm going to close this issue because the libxcb pinning isn't really the root cause of the issues mentioned above, in my view. To keep the discussion all in one place, any followups happen in the discussion for conda-forge/graphviz-feedstock#35.

**Closed as completed by pkgw** 2021-03-22 14:53 UTC
